# Gunakan hanya provider Node
providers = ["node"]

[phases.setup]
# Ambil Node 20 LTS + pnpm langsung dari nixpkgs
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
# Instal dependensi menggunakan pnpm
cmds = [
  "pnpm install --frozen-lockfile --ignore-scripts"
]
# Simpan cache agar build berikutnya lebih cepat
cacheDirs = [".pnpm-store"]

[phases.build]
cmds = [
  "pnpm run build"            # menjalankan script build di package.json
]

[start]
cmd = "pnpm run start"
